language: python
python:
  - "2.7"
  - "3.8"
  # - "nightly"
  #- "pypy"
  # - "pypy3"
sudo: false
env:
  global:
    - PYTHONIOENCODING=UTF-8
    - USERDOMAIN=TRAVIS
    - CHECK_NAMES=TRUE
    - LAZY=FALSE
  matrix:
    - STRATEGY=SYNC SERVER=EDIR DECODER=INTERNAL
    - STRATEGY=SYNC SERVER=EDIR DECODER=PYASN1
    #- STRATEGY=SYNC SERVER=AD DECODER=INTERNAL
    #- STRATEGY=SYNC SERVER=AD DECODER=PYASN1
    - STRATEGY=ASYNC SERVER=EDIR DECODER=INTERNAL
    - STRATEGY=ASYNC SERVER=EDIR DECODER=PYASN1
    #- STRATEGY=ASYNC SERVER=AD DECODER=INTERNAL
    #- STRATEGY=ASYNC SERVER=AD DECODER=PYASN1
    - STRATEGY=RESTARTABLE SERVER=EDIR DECODER=INTERNAL
    - STRATEGY=RESTARTABLE SERVER=EDIR DECODER=PYASN1
    #- STRATEGY=RESTARTABLE SERVER=AD DECODER=INTERNAL
    #- STRATEGY=RESTARTABLE SERVER=AD DECODER=PYASN1
    - STRATEGY=REUSABLE SERVER=EDIR DECODER=INTERNAL
    - STRATEGY=REUSABLE SERVER=EDIR DECODER=PYASN1
    #- STRATEGY=REUSABLE SERVER=AD DECODER=INTERNAL
    #- STRATEGY=REUSABLE SERVER=AD DECODER=PYASN1

install:
  - "pip install ."
  - "pip list"
script:
  - nosetests -s test
